# name: learn-github-actions
# run-name: ${{ github.actor }} is learning GitHub Actions
# on: [push]
# jobs:
#   check-bats-version:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v4
#       - uses: actions/setup-node@v3
#         with:
#           node-version: '14'
#       - run: npm install -g bats
#       - run: bats -v


name: MAKEFILE test

on: [push]

jobs:
    check-makefile:
      strategy:
        matrix:
          os: [macos-latest, ubuntu-latest]
          # bash: [3.2, 4.2, 5.0, 5.2]
      runs-on: ${{ matrix.os }}
      steps:
          - uses: actions/checkout@v3
          # - name: To install make
          #   run: brew install make
          # - name: Compiling Make
          #   run: make
          # - name: Installing app
          #   run: make install
          # - name: Uninstalling app
          #   run: make uninstall
          - name: bash version
            run: echo $BASH_VERSION
          - name: bash verinfo
            run: echo $BASH_VERINFO
          - name: coreutils version
            run: ls --version 2> /dev/null || gls --version
