name: Comment on PR

on:
    pull_request:
        branches:
            - 'main'

jobs:
    pr_comment:
        name: Create Commnent on PR
        runs-on: ubuntu-latest
        permissions:
            contents: write
        steps:
          - name: add comment to PR
            run: |
              gh api -X POST \
              /repos/${OWNER}/${REPO}/issues/${ISSUE_NUMBER}/comments \
              -f body='Comment form pr_comment workflow'
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              OWNER: ${{ github.repository_owner }}
              REPOSITORY: ${{ github.event.repository.name }}
              ISSUE_NUMBER: ${{ github.event.number }}
