name: Create Release

on:
    push:
        tags:
          - 'v*'

jobs:
    release:
        name: Create release
        runs-on: ubuntu-latest
        permissions: 
            contents: write
        steps:
          - name: Checkout code
            uses: actions/checkout@v3

          # - name: Create Github release
          #   id: create_release
          #   uses: actions/create-release@v1
          #   env:
          #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          #   with:
          #     tag_name: ${{ github.ref }}
          #     release_name: Release ${{ github.ref }}
          #     body: |
          #       Changes in this release
          #       - First change
          #       - Second change
          #       - Third changes
          #     draft: false
          #     prerelease: false

          - name: Run API call to get changelog
            uses: actions/github-script@v7
            with: 
              github-token: ${{ secrets.GITHUB_TOKEN }}
              script: |
                await github.request("POST /repos/${{ github.repository }}/releases", { 
                  tag_name: '${{ github.ref_name }}',
                  name: 'Test '+'${{ github.ref_name}}',
                  draft: false,
                  prerelease: false,
                  generate_release_notes: true,
                });
          - name: adding commits since last release
            uses: actions/publish-actions@v0.2.2
            with:
              source-tag: '${{ github.ref_name }}'

