name: Shellcheck

on: [push]


jobs:
  shellcheck:
      name: Shellcheck
      runs-on: macos-latest
      steps:
      - uses: actions/checkout@v4
      - name: Run shellcheck
        uses: ludeeus/action-shellcheck@master
        with: 
          scandir: './src'